query1:
  SELECT
    catalog_name,
    schema_name,
    schema_owner,
    creation_time,
    last_modified_time,
    location
  FROM
    {region}.INFORMATION_SCHEMA.SCHEMATA
query2 :
  SELECT
  creation_time,
  a.project_id,
  project_number,
  user_email,
  job_id,
  job_type,
  parent_job_id,
  session_info,
  statement_type,
  start_time,
  end_time,
  query,
  state,
  reservation_id,
  total_bytes_processed,
  a.total_slot_ms,
  total_modified_partitions,
  total_bytes_billed,
  error_result.reason AS error_result_reason,
  error_result.location AS error_result_location,
  error_result.debug_info AS error_result_debug_info,
  error_result.message AS error_result_message,
  cache_hit,
  destination_table.project_id AS destination_project_id,
  destination_table.dataset_id AS destination_dataset_id,
  destination_table.table_id AS destination_table_id,
  referenced_tables,
  labels,
  timeline,
  job_stages
  FROM
  {region}.INFORMATION_SCHEMA.JOBS_BY_PROJECT AS a
  WHERE
  creation_time > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
query3:
  SELECT
  SPECIFIC_CATALOG,
  SPECIFIC_SCHEMA,
  SPECIFIC_NAME,
  ROUTINE_CATALOG,
  ROUTINE_SCHEMA,
  ROUTINE_NAME,
  ROUTINE_TYPE,
  DATA_TYPE,
  ROUTINE_BODY,
  ROUTINE_DEFINITION,
  EXTERNAL_LANGUAGE,
  IS_DETERMINISTIC,
  SECURITY_TYPE,
  CREATED,
  LAST_ALTERED,
  DDL
  FROM
  {region}.INFORMATION_SCHEMA.ROUTINES
query4:
  SELECT
  TABLE_CATALOG,
  TABLE_SCHEMA,
  TABLE_NAME,
  COLUMN_NAME,
  ORDINAL_POSITION,
  IS_NULLABLE,
  DATA_TYPE,
  IS_GENERATED,
  GENERATION_EXPRESSION,
  IS_STORED,
  IS_HIDDEN,
  IS_UPDATABLE,
  IS_SYSTEM_DEFINED,
  IS_PARTITIONING_COLUMN,
  CLUSTERING_ORDINAL_POSITION
  FROM
  {region}.INFORMATION_SCHEMA.COLUMNS
query5:
  SELECT
  TABLE_CATALOG,
  TABLE_SCHEMA,
  TABLE_NAME,
  VIEW_DEFINITION,
  CHECK_OPTION,
  USE_STANDARD_SQL
  FROM
  {region}.INFORMATION_SCHEMA.VIEWS
query6:
  SELECT
  project_id,
  dataset_id,
  table_id,
  creation_time,
  last_modified_time,
  row_count,
  size_bytes,
  type
  FROM
  {project_id}.{dataset}.__TABLES__
query7:
  SELECT
  TABLE_CATALOG,
  TABLE_SCHEMA,
  TABLE_NAME,
  TABLE_TYPE,
  IS_INSERTABLE_INTO,
  IS_TYPED,
  CREATION_TIME,
  DDL
  FROM
  {region}.INFORMATION_SCHEMA.TABLES





